version: '3'

volumes:
  data-volume:

services:
  database:
    image: mysql:5.7.16
    environment:
      MYSQL_DATABASE: IE
      MYSQL_ROOT_PASSWORD: mypassword
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    expose:
      - 3306
    ports:
      - 9000:3306
    volumes:
      - data-volume:/var/lib/mysql


  backend:
    image: joboonja-backend
    build: ./IE-project
    depends_on:
      - database
    expose: 
      - 8080
    ports: 
      - 8080:8080
    links:
      - database

  frontend:
    image: joboonja-frontend
    build: ./IE-frontend
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - backend
